2015-12-31 11:04:43.377 nodejs.ErrorException: Error: demo error
    at Object.callee$0$0$ (/Users/xuanyong/Desktop/kaola/app.js:51:9)
    at tryCatch (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:323:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:94:21)
    at onFulfilled (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:65:19)
    at /Users/xuanyong/Desktop/kaola/node_modules/co/index.js:54:5
    at new Promise (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:182:7)
    at Object.co (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:118:63)
    at next (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:69:7)
    at run (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:89:39)
    at /usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/$.microtask.js:17:13)
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
pid: 33816
Host: xuanyongdeMacBook-Air.local
URL:
Data: ''
2015-12-31 11:04:43.377

2015-12-31 11:04:44.592 nodejs.ErrorException: Error: demo error
    at Object.callee$0$0$ (/Users/xuanyong/Desktop/kaola/app.js:51:9)
    at tryCatch (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:323:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:94:21)
    at onFulfilled (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:65:19)
    at /Users/xuanyong/Desktop/kaola/node_modules/co/index.js:54:5
    at new Promise (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:182:7)
    at Object.co (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:118:63)
    at next (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:69:7)
    at run (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:89:39)
    at /usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/$.microtask.js:17:13)
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
pid: 33816
Host: xuanyongdeMacBook-Air.local
URL:
Data: ''
2015-12-31 11:04:44.592

2015-12-31 11:08:53.981 nodejs.ReferenceErrorException: ReferenceError: log is not defined
    at Object.callee$0$0$ (/Users/xuanyong/Desktop/kaola/app.js:51:15)
    at tryCatch (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:323:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:94:21)
    at onFulfilled (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:65:19)
    at /Users/xuanyong/Desktop/kaola/node_modules/co/index.js:54:5
    at new Promise (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:182:7)
    at Object.co (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:118:63)
    at next (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:69:7)
    at run (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:89:39)
    at /usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/$.microtask.js:17:13)
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
pid: 33885
Host: xuanyongdeMacBook-Air.local
URL:
Data: ''
2015-12-31 11:08:53.981
2015-12-31 15:36:43.327 nodejs.ReferenceErrorException: ReferenceError: pageName is not defined
    at Object.render (/Users/xuanyong/Desktop/kaola/utils/render.js:7:28)
    at Object.callee$0$0$ (/Users/xuanyong/Desktop/kaola/routes/index.js:10:16)
    at tryCatch (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:323:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:94:21)
    at Object.allowedMethods (/Users/xuanyong/Desktop/kaola/node_modules/koa-router/lib/router.js:369:12)
    at [object Generator].next (native)
    at Object.dispatch (/Users/xuanyong/Desktop/kaola/node_modules/koa-router/lib/router.js:331:14)
    at [object Generator].next (native)
    at onFulfilled (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:65:19)
    at /Users/xuanyong/Desktop/kaola/node_modules/co/index.js:54:5
    at new Promise (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:182:7)
    at Object.co (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:118:63)
    at next (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:69:7)
    at /Users/xuanyong/Desktop/kaola/node_modules/co/index.js:54:5
    at new Promise (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:182:7)
    at Object.co (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:118:63)
    at next (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:69:7)
pid: 37484
Host: xuanyongdeMacBook-Air.local
URL: 
Data: ''
2015-12-31 15:36:43.327

2015-12-31 17:34:47.236 nodejs.TypeErrorException: TypeError: You may only yield a function, promise, generator, array, or object, but the following object was passed: "undefined"
    at next (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:101:25)
    at onFulfilled (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:69:7)
    at /Users/xuanyong/Desktop/kaola/node_modules/co/index.js:54:5
    at new Promise (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:182:7)
    at Object.co (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:118:63)
    at next (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:69:7)
    at /Users/xuanyong/Desktop/kaola/node_modules/co/index.js:54:5
    at new Promise (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:182:7)
    at Object.co (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:118:63)
    at next (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:69:7)
    at run (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:89:39)
    at /usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/$.microtask.js:17:13)
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
pid: 38087
Host: xuanyongdeMacBook-Air.local
URL: 
Data: ''
2015-12-31 17:34:47.236

2015-12-31 17:35:18.194 nodejs.TypeErrorException: TypeError: You may only yield a function, promise, generator, array, or object, but the following object was passed: "undefined"
    at next (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:101:25)
    at onFulfilled (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:69:7)
    at /Users/xuanyong/Desktop/kaola/node_modules/co/index.js:54:5
    at new Promise (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:182:7)
    at Object.co (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:118:63)
    at next (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:69:7)
    at /Users/xuanyong/Desktop/kaola/node_modules/co/index.js:54:5
    at new Promise (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:182:7)
    at Object.co (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:118:63)
    at next (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:69:7)
    at run (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:89:39)
    at /usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/$.microtask.js:17:13)
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
pid: 38093
Host: xuanyongdeMacBook-Air.local
URL: 
Data: ''
2015-12-31 17:35:18.194

2015-12-31 17:35:50.062 nodejs.TypeErrorException: TypeError: You may only yield a function, promise, generator, array, or object, but the following object was passed: "undefined"
    at next (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:101:25)
    at onFulfilled (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:69:7)
    at /Users/xuanyong/Desktop/kaola/node_modules/co/index.js:54:5
    at new Promise (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:182:7)
    at Object.co (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:118:63)
    at next (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:69:7)
    at /Users/xuanyong/Desktop/kaola/node_modules/co/index.js:54:5
    at new Promise (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:182:7)
    at Object.co (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:118:63)
    at next (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:69:7)
    at run (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:89:39)
    at /usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/$.microtask.js:17:13)
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
pid: 38100
Host: xuanyongdeMacBook-Air.local
URL: 
Data: ''
2015-12-31 17:35:50.062

2015-12-31 18:11:36.798 nodejs.TypeErrorException: TypeError: You may only yield a function, promise, generator, array, or object, but the following object was passed: "undefined"
    at next (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:101:25)
    at onFulfilled (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:69:7)
    at /Users/xuanyong/Desktop/kaola/node_modules/co/index.js:54:5
    at new Promise (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:182:7)
    at Object.co (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:118:63)
    at next (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:69:7)
    at /Users/xuanyong/Desktop/kaola/node_modules/co/index.js:54:5
    at new Promise (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:182:7)
    at Object.co (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:118:63)
    at next (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/xuanyong/Desktop/kaola/node_modules/co/index.js:69:7)
    at run (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:89:39)
    at /usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/$.microtask.js:17:13)
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
pid: 38242
Host: xuanyongdeMacBook-Air.local
URL: 
Data: ''
2015-12-31 18:11:36.798

